name: Backend CI

on:
  push:
    paths:
      - backend/**
      - .github/**
  pull_request:
    paths:
      - backend/**
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu", "windows", "macos"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go build .
        working-directory: backend
