name: Backend CD

on:
  push:
    paths:
      - backend/**
      - .github/**
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Login
        env:
          DOCKER_USERNAME: nycode
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - name: Build and Push
        run: ./build.sh
        shell: bash
        working-directory: backend
